FROM golang

ARG SSH_PRIVATE_KEY

RUN apt-get update \
    && apt-get install -y automake g++ git make pkg-config supervisor ssh

## Adding SSH keys for accessing private repo
RUN mkdir /root/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# Actual hindsight install
RUN mkdir /hindsight
WORKDIR /hindsight
RUN git clone git@github.com:SimBioSysLab/hindsight.git ; \
    cd hindsight/client ; \
    make && make install; ldconfig ;\
    cd ../agent && go build -o coordinator cmd/coordinator/main.go; \
    cd ../agent && go build -o collector cmd/collector/main.go; \
    mv coordinator /usr/local/bin/ ; \
    mv collector /usr/local/bin/ ;

COPY ./supervisor_conf/hindsight_coordinator.conf /etc/coordinator.conf
COPY ./supervisor_conf/hindsight_collector.conf /etc/collector.conf

WORKDIR /hindsight