FROM golang

ARG SSH_PRIVATE_KEY

RUN apt-get update \
    && apt-get install -y automake g++ git make pkg-config supervisor ssh

# Installing Hindsight
RUN mkdir /hindsight
WORKDIR /hindsight
RUN git clone https://gitlab.mpi-sws.org/cld/tracing/hindsight.git ; \
    cd hindsight/client ; \
    make && make install; ldconfig ;\
    cd ../agent && go build -o coordinator cmd/coordinator/main.go; \
    cd ../agent && go build -o collector cmd/collector/main.go; \
    mv coordinator /usr/local/bin/ ; \
    mv collector /usr/local/bin/ ;

COPY ./supervisor_conf/hindsight_coordinator.conf /etc/coordinator.conf
COPY ./supervisor_conf/hindsight_collector.conf /etc/collector.conf

WORKDIR /hindsight